title: Ben Beasley # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Computer science student and hobbyist game developer.
  <br><br>
  Most of my GitHub projects are private to the profile there is quite bare.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
