title: Ben Beasley # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Computer science student and hobbyist game developer in the UK.
  <br><br>
  Currently studying at the University of Southampton
  <br><br>
  <h3>Contact</h3>
  <a href="mailto:benjaminjbeasley@gmail.com">benjaminjbeasley@gmail.com</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
